// automatically generated by the FlatBuffers compiler, do not modify
import { flatbuffers as fbs }  from "./flatbuffers.js"
/**
 * @constructor
 */
export namespace base.genflat{
export class Vec3 {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Vec3
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Vec3 {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns number
 */
x():number {
  return this.bb!.readFloat32(this.bb_pos);
};

/**
 * @returns number
 */
y():number {
  return this.bb!.readFloat32(this.bb_pos + 4);
};

/**
 * @returns number
 */
z():number {
  return this.bb!.readFloat32(this.bb_pos + 8);
};

/**
 * @param flatbuffers.Builder builder
 * @param number x
 * @param number y
 * @param number z
 * @returns flatbuffers.Offset
 */
static createVec3(builder:flatbuffers.Builder, x: number, y: number, z: number):flatbuffers.Offset {
  builder.prep(4, 12);
  builder.writeFloat32(z);
  builder.writeFloat32(y);
  builder.writeFloat32(x);
  return builder.offset();
};

}
}
declare var flatbuffers:any
flatbuffers = fbs;
/**
 * @constructor
 */
export namespace base.genflat{
export class Request {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Request
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Request {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Request= obj
 * @returns Request
 */
static getRootAsRequest(bb:flatbuffers.ByteBuffer, obj?:Request):Request {
  return (obj || new Request).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns number
 */
msgID():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 1;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
msgType():string|null
msgType(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
msgType(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param base.genflat.Payload= obj
 * @returns base.genflat.Payload|null
 */
msgContent(obj?:base.genflat.Payload):base.genflat.Payload|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new base.genflat.Payload).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startRequest(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param flatbuffers.Builder builder
 * @param number msgID
 */
static addMsgID(builder:flatbuffers.Builder, msgID:number) {
  builder.addFieldInt32(0, msgID, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset msgTypeOffset
 */
static addMsgType(builder:flatbuffers.Builder, msgTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, msgTypeOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset msgContentOffset
 */
static addMsgContent(builder:flatbuffers.Builder, msgContentOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, msgContentOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createRequest(builder:flatbuffers.Builder, msgID:number, msgTypeOffset:flatbuffers.Offset, msgContentOffset:flatbuffers.Offset):flatbuffers.Offset {
  Request.startRequest(builder);
  Request.addMsgID(builder, msgID);
  Request.addMsgType(builder, msgTypeOffset);
  Request.addMsgContent(builder, msgContentOffset);
  return Request.endRequest(builder);
}
}
}
/**
 * @constructor
 */
export namespace base.genflat{
export class Payload {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Payload
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Payload {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Payload= obj
 * @returns Payload
 */
static getRootAsPayload(bb:flatbuffers.ByteBuffer, obj?:Payload):Payload {
  return (obj || new Payload).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
service():string|null
service(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
service(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
methodName():string|null
methodName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
methodName(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param number index
 * @param base.genflat.Vec3= obj
 * @returns base.genflat.Vec3
 */
args(index: number, obj?:base.genflat.Vec3):base.genflat.Vec3|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new base.genflat.Vec3).__init(this.bb!.__vector(this.bb_pos + offset) + index * 12, this.bb!) : null;
};

/**
 * @returns number
 */
argsLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startPayload(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset serviceOffset
 */
static addService(builder:flatbuffers.Builder, serviceOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, serviceOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset methodNameOffset
 */
static addMethodName(builder:flatbuffers.Builder, methodNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, methodNameOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset argsOffset
 */
static addArgs(builder:flatbuffers.Builder, argsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, argsOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startArgsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(12, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endPayload(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createPayload(builder:flatbuffers.Builder, serviceOffset:flatbuffers.Offset, methodNameOffset:flatbuffers.Offset, argsOffset:flatbuffers.Offset):flatbuffers.Offset {
  Payload.startPayload(builder);
  Payload.addService(builder, serviceOffset);
  Payload.addMethodName(builder, methodNameOffset);
  Payload.addArgs(builder, argsOffset);
  return Payload.endPayload(builder);
}
}
}
